In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [14]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [26]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
type(ones)

numpy.ndarray

In [28]:
zeros = np.zeros((2,3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range_array = np.arange(0,100,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [35]:
random_array = np.random.randint(0,10,size = (3,5))
random_array

array([[6, 7, 9, 6, 6],
       [5, 6, 6, 5, 8],
       [6, 9, 4, 6, 7]])

In [36]:
random_array.size

15

In [37]:
random_array.shape

(3, 5)

In [38]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.64660872, 0.54511562, 0.38047789],
       [0.26593433, 0.07973204, 0.10247594],
       [0.93962189, 0.85966808, 0.69355828],
       [0.22580613, 0.08196439, 0.97753855],
       [0.21583437, 0.64610061, 0.59602331]])

In [39]:
random_array2.shape

(5, 3)

In [41]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.40621934, 0.40319377, 0.02986967],
       [0.45735595, 0.78170922, 0.20512011],
       [0.16962769, 0.37573553, 0.51532995],
       [0.676889  , 0.39096168, 0.00254197],
       [0.09394515, 0.63514121, 0.58562807]])

In [56]:
# Pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
np.random.seed(2)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987]])

## 3.Viewing arrays and Matrices

In [65]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a4 = np.random.randint(10,size = (2,3,4,5))

In [67]:
a4

array([[[[7, 6, 1, 3, 5],
         [8, 4, 6, 3, 9],
         [2, 0, 4, 2, 4],
         [1, 7, 8, 2, 9]],

        [[8, 7, 1, 6, 8],
         [5, 9, 9, 9, 3],
         [0, 0, 2, 8, 8],
         [2, 9, 6, 5, 6]],

        [[6, 6, 3, 8, 2],
         [1, 4, 8, 1, 6],
         [9, 5, 1, 2, 4],
         [7, 6, 4, 5, 8]]],


       [[[3, 0, 0, 5, 7],
         [5, 0, 8, 6, 5],
         [1, 7, 4, 3, 6],
         [1, 4, 0, 8, 5]],

        [[4, 2, 9, 7, 1],
         [9, 2, 1, 0, 7],
         [1, 8, 9, 0, 7],
         [0, 5, 2, 5, 1]],

        [[3, 3, 1, 8, 6],
         [8, 1, 5, 7, 0],
         [9, 1, 5, 9, 2],
         [0, 0, 4, 6, 3]]]])

In [74]:
# Get the first 4 numbers of the inner most array
a4[:,:,:,:4]

array([[[[7, 6, 1, 3],
         [8, 4, 6, 3],
         [2, 0, 4, 2],
         [1, 7, 8, 2]],

        [[8, 7, 1, 6],
         [5, 9, 9, 9],
         [0, 0, 2, 8],
         [2, 9, 6, 5]],

        [[6, 6, 3, 8],
         [1, 4, 8, 1],
         [9, 5, 1, 2],
         [7, 6, 4, 5]]],


       [[[3, 0, 0, 5],
         [5, 0, 8, 6],
         [1, 7, 4, 3],
         [1, 4, 0, 8]],

        [[4, 2, 9, 7],
         [9, 2, 1, 0],
         [1, 8, 9, 0],
         [0, 5, 2, 5]],

        [[3, 3, 1, 8],
         [8, 1, 5, 7],
         [9, 1, 5, 9],
         [0, 0, 4, 6]]]])

## 4. Manipulating & comparing arrays

In [75]:
a1

array([1, 2, 3])

In [77]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [78]:
a1+ones

array([2., 3., 4.])

In [79]:
a1-ones

array([0., 1., 2.])

In [80]:
a1*ones

array([1., 2., 3.])

In [84]:
a1

array([1, 2, 3])

In [85]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [86]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [89]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

### Aggregation
Aggregation = performing the same operation on a number of things

In [91]:
listy_list = [1,2,3]
type(listy_list)

list

In [92]:
sum(listy_list)

6

In [94]:
sum(a1)

6

In [95]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Pyhton datatypes and use and NumPy's methods on NumPy arrays (`np.sum()`).

In [97]:
# Creative a massive NumPy Array
massive_array = np.random.random(100000)
massive_array[:10]

array([0.94916992, 0.22722088, 0.62527046, 0.30269309, 0.37418237,
       0.29054822, 0.62426065, 0.86241242, 0.1438776 , 0.19743849])

In [98]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

7.37 ms ± 258 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.8 μs ± 231 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [99]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [100]:
np.mean(a2)

3.6333333333333333

In [101]:
np.max(a2)

6.5

In [102]:
np.min(a2)

1.0

In [105]:
#Standart deviation = a measure of how spread out a group of number is from the mean
np.std(a2)

1.8226964152656422

In [107]:
#Variance = measure of the average degree to which each number is different than the mean
#Higher variance = wider range of numbers
#Lower variance = lower range of number
np.var(a2)

3.3222222222222224

In [108]:
#Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [110]:
#Demo of std and var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [111]:
np.var(high_var_array),np.var(low_var_array)

(4296133.472222221, 8.0)

In [112]:
np.std(high_var_array),np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [113]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [114]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [116]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [124]:
a3.shape

(2, 3, 3)

In [126]:
a3.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

## Dot Product

In [127]:
np.random.seed(0)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [128]:
mat1.shape,mat2.shape

((5, 3), (5, 3))

In [129]:
#Element wise multiplication
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [130]:
#Dot product
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [131]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [132]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [136]:
mat3 = np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [138]:
mat3.shape

(5, 5)

## Dot Product Example

In [141]:
np.random.seed(0)
# Number of jars sold
sales_amount = np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [143]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon","Tues","Wed","Thurs","Fri"],
                           columns=["Almond","Peanut Butter"," Cashew Butter"])
weekly_sales

Almond  Peanut Butter   Cashew Butter
Mon        12             15               0
Tues        3              3               7
Wed         9             19              18
Thurs       4              6              12
Fri         1              6               7

In [145]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [151]:
# Create butter_prices Dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond","Peanut Butter"," Cashew Butter"])
butter_prices

Almond  Peanut Butter   Cashew Butter
Price      10              8              12

In [154]:
sales_amount.shape,prices.shape

((5, 3), (3,))

In [152]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [157]:
#Shapes are not aligned let's transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [160]:
#Create daily_sales
butter_prices.shape,weekly_sales.shape

((1, 3), (5, 3))

In [161]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [162]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [164]:
weekly_sales["Total ($)"] = daily_sales.T

In [165]:
weekly_sales

Almond  Peanut Butter   Cashew Butter  Total ($)
Mon        12             15               0        240
Tues        3              3               7        138
Wed         9             19              18        458
Thurs       4              6              12        232
Fri         1              6               7        142

## Practical Example Numpy in Action 

<img src="images/panda.png"/>

In [174]:
# Turn an image int oa NumPy array
from matplotlib.image import imread
panda = imread('images/panda.png')

In [176]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [177]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png"/>

In [179]:
car = imread("images/car-photo.png")

<img src="images/dog-photo.png"/>

In [180]:
dog = imread("images/dog-photo.png")

In [181]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274